# Site settings
title: Tabiji
email:
description: ENRICH YOUR LIFE THROUGH YOUR TRAVEL
baseurl: ""
# baseurl: "https://daichancorgi.github.io/tabiji-lp" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# default language is english.
languages: ["en", "ja"]

# Github上の公開用のディレクトリを指定
destination:  docs

# i18nの対象外ディレクトリ
exclude_from_localizations: [
  "js", "css", "font-awesome", "fonts",
  "Rakefile", "README.md", "Gemfile", "docs"
]

twitter_username:
github_username:

# Build settings
markdown: kramdown

plugins: 
  - jekyll-multiple-languages-plugin